### ISSUE TITLE
missing code in the example

### ISSUE THREAD

**Issue by syrakozz** [antoniocasero/ACPReminder#8]
you must add this 
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

    if ([UIApplication instancesRespondToSelector:@selector(registerUserNotificationSettings:)]){
        [application registerUserNotificationSettings:[UIUserNotificationSettings settingsForTypes:UIUserNotificationTypeAlert|UIUserNotificationTypeBadge|UIUserNotificationTypeSound categories:nil]];
    }
    

    return YES;
}

the delegate to work

**Comment by antoniocasero** [comment]
Thanks, the code has been updated
